### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JinKun-Yong** [transistorsoft/flutter_background_geolocation_firebase#23]
Unable to call flutter pub get with  background_geolocation_firebase: ^0.2.0
```
The plugin `background_geolocation_firebase` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
```
Here's my flutter doctor:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.2.1 20D74 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.60.1)
[✓] Connected device (2 available)

• No issues found!

**Comment by christocracy** [comment]
I see.  It will be upgraded and released soon.

**Comment by christocracy** [comment]
Try installing from branch `plugin-v2`.

*pubspec.yaml*
```yaml
dependencies:
  flutter_background_geolocation_firebase:
    git:
      url: https://github.com/transistorsoft/flutter_background_geolocation_firebase.git
      ref:  plugin-v2
```
